USE programmers_groupBy;

CREATE TABLE ANIMAL_OUTS (
    ANIMAL_ID VARCHAR(20) PRIMARY KEY NOT NULL,
    ANIMAL_TYPE VARCHAR(20) NOT NULL,
    DATETIME DATETIME NOT NULL,
    NAME VARCHAR(50),
    SEX_UPON_OUTCOME VARCHAR(20) NOT NULL
);

SHOW TABLES;

INSERT INTO ANIMAL_OUTS (ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME, SEX_UPON_OUTCOME)
VALUES 
    ('A354597', 'Cat', '2014-06-03 12:30:00', 'Ariel', 'Spayed Female'),
    ('A362707', 'Dog', '2017-01-10 10:44:00', 'Girly Girl', 'Spayed Female'),
    ('A370507', 'Cat', '2015-08-15 09:24:00', 'Emily', '');

SELECT * FROM ANIMAL_OUTS;

SELECT 
    DATE_FORMAT(DATETIME, '%H') AS HOUR,
    COUNT(*) AS COUNT
FROM
    ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN '9' AND '19'
GROUP BY HOUR
ORDER BY 1;