USE programmers_isNull;

CREATE TABLE USER_INFO (
	USER_ID INTEGER PRIMARY KEY NOT NULL,
    GENDER TINYINT(1),
    AGE INTEGER,
    JOINED DATE NOT NULL
);

SHOW TABLES;

INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES 
(1, 1, 26, '2021-06-01'),
(2, NULL, NULL, '2021-07-25'),
(3, 1, NULL, '2021-07-30'),
(4, 0 , 31, '2021-08-03');

SELECT * FROM USER_INFO;

SELECT 
    COUNT(*) AS USERS
FROM
    USER_INFO
WHERE
    AGE IS NULL;