USE programmers_isNull;

CREATE TABLE ANIMAL_INS (
    ANIMAL_ID VARCHAR(20) PRIMARY KEY NOT NULL,
    ANIMAL_TYPE VARCHAR(20) NOT NULL,
    DATETIME DATETIME NOT NULL,
    INTAKE_CONDITION VARCHAR(20) NOT NULL,
    NAME VARCHAR(50),
    SEX_UPON_INTAKE VARCHAR(20) NOT NULL
);

SHOW TABLES;

INSERT INTO ANIMAL_INS (ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE) VALUES
('A368930', 'Dog', '2014-06-08 13:20:00', 'Normal', NULL, 'Spayed Female'),
('A524634', 'Dog', '2015-01-02 18:54:00', 'Normal', '*Belle', 'Intact Female'),
('A465637', 'Dog', '2017-06-04 08:17:00', 'Injured', '*Commander', 'Neutered Male');

SELECT * FROM ANIMAL_INS;

SELECT 
    ANIMAL_ID
FROM
    ANIMAL_INS
WHERE
    NAME IS NULL;
