CREATE DATABASE programmers_sum_max_min;
USE programmers_sum_max_min;

CREATE TABLE PRODUCT (
	PRODUCT_ID INTEGER PRIMARY KEY NOT NULL,
    PRODUCT_CODE VARCHAR(8) NOT NULL,
    PRICE INTEGER NOT NULL
);

SHOW TABLES;

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRICE) VALUES
(1, 'A1000001', 10000),
(2, 'A2000005', 9000),
(3, 'C1000006', 22000);

SELECT * FROM PRODUCT;

SELECT PRICE AS MAX_PRICE FROM PRODUCT ORDER BY PRICE DESC limit 1;

SELECT MAX(PRICE) AS MAX_PRICE FROM PRODUCT

