CREATE DATABASE programmers_string_date;
USE programmers_string_date;

CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY (
	HISTORY_ID INTEGER PRIMARY KEY NOT NULL,
    CAR_ID INTEGER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL
);

SHOW TABLES;

INSERT INTO CAR_RENTAL_COMPANY_RENTAL_HISTORY (HISTORY_ID, CAR_ID, START_DATE, END_DATE) VALUES 
(1, 4, "2022-09-27", "2022-11-27"),
(2, 3, "2022-10-03", "2022-11-04"),
(3, 2, "2022-09-05", "2022-09-05"),
(4, 1, "2022-09-01", "2022-09-30"),
(5, 3, "2022-09-16", "2022-10-15");

SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;

SELECT HISTORY_ID, CAR_ID, 
       DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,   
       DATE_FORMAT(END_DATE,'%Y-%m-%d') AS END_DATE,
       IF( (TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1)>=30, 
           '장기 대여','단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC;

SELECT 
    HISTORY_ID,
    CAR_ID,
    DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
    DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    -- IF(DATEDIFF(END_DATE, START_DATE) + 1 >= 30,
--         '장기 대여',
--         '단기 대여') AS RENT_TYPE
	CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '장기 대여' 
	ELSE '단기 대여' 
	END AS REND_TYPE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    DATE_FORMAT(START_DATE, '%Y-%m') = '2022-09'
ORDER BY HISTORY_ID DESC;

