USE programmers_select;

CREATE TABLE CAR_RENTAL_COMPANY_CAR (
    CAR_ID INTEGER PRIMARY KEY NOT NULL,
    CAR_TYPE VARCHAR(255) NOT NULL,
    DAILY_FEE INTEGER NOT NULL,
    OPTIONS VARCHAR(255) NOT NULL
);

SHOW TABLES;

INSERT INTO CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS) 
VALUES
(1, '세단', 16000, '가죽시트,열선시트,후방카메라'),
(2, 'SUV', 14000, '스마트키,네비게이션,열선시트'),
(3, 'SUV', 22000, '주차감지센서,후방카메라,가죽시트');

SELECT * FROM CAR_RENTAL_COMPANY_CAR;

SELECT 
    ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
FROM
    CAR_RENTAL_COMPANY_CAR
WHERE
    CAR_TYPE = 'SUV';

